filename = "new-testament-greek-vocabulary.apkg"

audio = []
video = []
image = []

[deck]
id = 1708324028
name = 'New Testament Greek'

[model]
id = 1495491169
name = 'Ancient Greek Vocabulary'
type = 'front-back'
guid = ['Phrase', 'Grammar', 'Translation']
styles = 'src/model/grek-simple.css'

[[model.templates]]
name = 'Recognize'
qfmt = 'src/model/recognize-qfmt-simple.html'
afmt = 'src/model/recognize-afmt-simple.html'

[[model.templates]]
name = 'Recall'
qfmt = 'src/model/recall-qfmt-simple.html'
afmt = 'src/model/recall-afmt-simple.html'

[[model.fields]]
name = 'Phrase'
markdown = false
template = 'src/template/Phrase.html'

[[model.fields]]
name = 'Grammar'
markdown = false
template = 'src/template/Grammar.html'

[[model.fields]]
name = 'Transcription'
markdown = false
template = 'src/template/Transcription.html'

[[model.fields]]
name = 'Translation'
markdown = false
template = 'src/template/Translation.html'

[[model.fields]]
name = 'Notes'
markdown = false
template = 'src/template/Notes.html'

# Sample vocabulary data

[[data]]
filename = 'src/vocabulary/noun.csv'
tags = ['Noun']

[[data]]
filename = 'src/vocabulary/verb.csv'
tags = ['Verb']
