version: '3'

vars:
  REGISTRY: registry.home.arpa:5000
  GIT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  BUILD_DATE:
    sh: date '+%Y-%m-%d'
  BASE_IMAGES: |
    jdp-python
    jdp-ubuntu
  APP_IMAGES: |
    jdp-fastapi
    jdp-build
    jdp-ebook

tasks:

  build-base:
    desc: Build base docker images
    cmds:
      - for:
          var: BASE_IMAGES
        task: build
        vars:
          IMAGE: '{{.ITEM}}'

  build-app:
    desc: Build application docker images
    cmds:
      - for:
          var: APP_IMAGES
        task: build
        vars:
          IMAGE: '{{.ITEM}}'

  push-base:
    desc: Push base docker images
    cmds:
      - for:
          var: BASE_IMAGES
        task: push
        vars:
          IMAGE: '{{.ITEM}}'

  build:
    desc: Build docker image (task build IMAGE=jdp-python)
    internal: true
    preconditions:
      - test -f {{.IMAGE}}/Dockerfile
    cmds:
      - docker buildx build --platform=linux/amd64 --build-arg VERSION={{.BUILD_DATE}} --build-arg BRANCH={{.GIT_BRANCH}} --build-arg COMMIT={{.GIT_COMMIT}} -t {{.IMAGE}} {{.IMAGE}}
    requires:
      vars:
        - GIT_BRANCH
        - GIT_COMMIT
        - BUILD_DATE
        - IMAGE

  push:
    desc: Push docker image (task push IMAGE=jdp-python)
    # internal: true
    cmds:
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.BUILD_DATE}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.BUILD_DATE}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}
    requires:
      vars:
        - REGISTRY
        - IMAGE
        - BUILD_DATE

  test:
    desc: Test docker image interactively (task test IMAGE=jdp-build)
    cmds:
      - docker run -it --rm --entrypoint /bin/bash -v ${PWD}:/workspace {{.IMAGE}}
    requires:
      vars:
        - IMAGE