version: '3'

tasks:

  jdp-buildenv:
    desc: Build jdp-buildenv image
    cmds:
      - task: build
        vars:
          IMAGE: jdp-buildenv

  jdp-buildenv-release:
    desc: Release jdp-buildenv image
    deps:
      - jdp-buildenv
    cmds:
      - task: release
        vars:
          IMAGE: jdp-buildenv

  jdp-dictionary:
    desc: Build jdp-dictionary image
    cmds:
      - task: build
        vars:
          IMAGE: jdp-dictionary

  jdp-dictionary-release:
    desc: Release jdp-dictionary image
    deps:
      - jdp-dictionary
    cmds:
      - task: release
        vars:
          IMAGE: jdp-dictionary

  jdp-jenkins:
    desc: Build jdp-jenkins image
    cmds:
      - task: build
        vars:
          IMAGE: jdp-jenkins

  jdp-jenkins-release:
    desc: Release jdp-jenkins image
    deps:
      - jdp-jenkins
    cmds:
      - task: release
        vars:
          IMAGE: jdp-jenkins

  build:
    desc: Build docker image
    internal: true
    preconditions:
      - test -f {{.IMAGE}}/Dockerfile
    cmds:
      - docker build -t {{.IMAGE}} {{.IMAGE}}
    requires:
      vars:
        - IMAGE

  release:
    desc: Release docker image
    internal: true
    vars:
      REGISTRY: registry.home.arpa:5000
    cmds:
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{now | date "2006-01-02"}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{now | date "2006-01-02"}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}
    requires:
      vars:
        - IMAGE