DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS language;
DROP TABLE IF EXISTS script;

CREATE TABLE script (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE language (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  script INTEGER NOT NULL,
  FOREIGN KEY (script) REFERENCES script (id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  lang_ctx INTEGER NOT NULL,
  FOREIGN KEY (lang_ctx) REFERENCES language (id)
);
